spring:
  application:
    name: kscn
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  banner:
    location: banner.txt
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 25GB

server:
  port: 8848
  servlet:
    context-path: /kscn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  expiration: 36000000

cookie:
  max-age: 36000
